version: "3.3"
services:
  airflow_db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=airflow
    # data in memory: will not persist
    tmpfs:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis

  # airflow containers
  airflow_webserver:
    build: .
    depends_on:
      - airflow_db
      - airflow_migrate
    ports:
      - 8080:8080
    command: airflow webserver
    env_file:
      - docker-compose.env
    volumes:
         - ./dags:/usr/local/airflow/dags


    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3


  airflow_scheduler:
    build: .
    depends_on:
      - airflow_db
      - airflow_migrate
    command: airflow scheduler
    env_file:
      - docker-compose.env
    volumes:
         - ./dags:/usr/local/airflow/dags

  airflow_worker:
    build: .
    depends_on:
      - airflow_db
      - airflow_migrate
      - airflow_scheduler
    command: airflow worker
    ports:
      - 8793:8793
    environment:
      - C_FORCE_ROOT=true
    env_file:
      - docker-compose.env
    volumes:
        - ./dags:/usr/local/airflow/dags


  airflow_migrate:
    build: .
    depends_on:
      - airflow_db
    env_file:
      - docker-compose.env
    command: airflow initdb
    volumes:
        - ./dags:/usr/local/airflow/dags
        